### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by steveklebanoff** [EnterpriseJSTutorial/koa-typescript-starter#1]
Following the instructions, I ran:

```
npm i
npm run watch-server
```

I get the error:
```
/Users/steve/koa-typescript-starter/src/server/logging.ts:18
async function logger(ctx, next) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Module.m._compile (/Users/steve/mycase/koa-pdf/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/steve/mycase/koa-pdf/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by steveklebanoff** [comment]
Whoops, was using an old version of node.  Might be helpful to have a `.nvmrc` in the repo
